### ISSUE TITLE
summon does not clean temp dir/files on SIGINT

### ISSUE THREAD

**Issue by LucaFilipozzi** [cyberark/summon#106]
If one interrupts a command invoked with summon, summon fails to clean its temporary directory and the files within.

summon should register a cleanup function that runs when a signal (SIGINT, SIGTERM, etc.) is received.

[This stackoverflow response](https://stackoverflow.com/a/18158859) provides an example of using os.Signal and signal.Notify.

**Comment by sgnn7** [comment]
@LucaFilipozzi Sorry for the late reply - we've been busy with other projects on the team. You make a good point here. We do this type of thing [elsewhere](https://github.com/cyberark/secretless-broker/blob/master/internal/pkg/plugin/manager.go#L122-L155) also and we can try to do it here, just need to find some time to get it implemented.

**Comment by ernst-at-tv2** [comment]
@sgnn7 any news regarding this issue and #108 ?

**Comment by sgnn7** [comment]
@ernst-at-tv2 there are no full-time devs on this project at the moment but I'll see about fixing it up this or next week.

**Comment by sgnn7** [comment]
@LucaFilipozzi / @ernst-at-tv2 / @moranbw

New version should have tempfile cleanups now: https://github.com/cyberark/summon/releases/tag/v0.8.0

Note that `SIGKILL` will not clean up due to the fact that [it bypasses the program completely](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html) but the other signals should work fine. Let me know if it works!

More info on `SIGKILL`:
```
The SIGKILL signal is used to cause immediate program termination. It cannot be handled or ignored, and is therefore always fatal. It is also not possible to block this signal.
```
