### ISSUE TITLE
Do files in /dev/shm (@SUMMONENVFILE) get cleaned up?

### ISSUE THREAD

**Issue by moranbw** [cyberark/summon#108]
Do files in /dev/shm get cleaned up somehow by OS or by Summon?  I am just curious, because I thought one of the main ideas behind this project was to avoid having plain-text representations of our secrets laying around on the OS.  But if we're just putting them in /dev/shm, aren't we essentially just moving the plain-text around, not eliminating it?

(disclaimer that I'm sort of a noob, and this may be a silly question)

**Comment by ernst-at-tv2** [comment]
we've experienced the same behaviour, could we get a reponse from the developers?

**Comment by sgnn7** [comment]
Hey @moranbw / @ernst-at-tv2,
`/dev/shm` folder in Linux is a shared memory device that looks like a regular filesystem but it's not a real disk. Anything created in this directory is only in memory (and not anywhere on disk) and vanishes as soon as your container or machine shuts down. Things placed in it still need specific IPC permissions and regular linux permissions to match up before it can be read. This is distinctly different from the #106 issue that may increase security a bit by doing the cleanup at exit-of-program time rather than at stop/restart of container/machine. I'll close this issue for now but feel free to reopen it if there's a specific issue with `/dev/shm` that needs addressing and hopefully I can get a bit of time this week or next to fixup #106.

A bit more info on `/dev/shm` can be found [here](https://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html)
