### ISSUE TITLE
User-owned tempfile contains secrets during runtime of `summon`

### ISSUE THREAD

**Issue by rami013** [cyberark/summon#177]
## Is your feature request related to a problem? Please describe

I noticed that when summon is used to communicate the secrets into docker containers, there is a temp file under user directory containing the sensitive data. When issuing a ps command on the host, one can see the full file path for the temp file, and try to access to the file to obtain the secrets.

## Describe the solution you would like

My question is how this temp file should be protected. I noticed that the file can only be read/write by the owner, but what would be the overall security model when calling summon wrapped docker images?

**Comment by sgnn7** [comment]
Hey @rami013,
Thank you for reaching out to us - user feedback is really important to us!

As for your question, we will _definitely_ need more info to even figure out if you're seeing something related to Summon or Docker itself.

> there is a temp file under user directory containing the sensitive data

Can you provide us with:
- [ ] What path is this file under?
- [ ] What OS is used for the host?
- [ ] What OS is running in the container?
- [ ] What flags are you using for `summon`?
- [ ] What kind of Docker installation and version are you using?
- [ ] What _exact_ Docker CLI invocation are you using?
- [ ] What summon provider are you using?
- [ ] Is there anything else specifically needed to be done see this file?

Thanks,
Srdjan

**Comment by rami013** [comment]
Sure, definitely.
This is a Mac laptop running Docker Desktop. I installed summon, and using local MacOs keyring provider.
This is command to run a container:

summon -p keyring.py docker run --env-file @SUMMONENVFILE docker/getting-started

This is my secret.yml:
KEY1: !var summon_test

where summon_test is an entry in the local keyring.

After issuing the above summon command, I issue 'ps' as follows:
ps -ef | grep getting

and in return, I see the following temp file:
/Users/<user name>/.tmp337142164/.summon521574883

and here is the content of the temp file when you do 'cat':
KEY1=***VERY SECRET***

which gives away all the secrets!

This temp file stays as long as the container is running. When the container stops, the temp file disappears as well.

**Comment by sgnn7** [comment]
Hey @rami013,
Oh I see what you mean - thank you for the additional info!

I apologize in advance but this may be a pretty long post but I think it's necessary to really get to the core of a bigger picture of "what is security?" and how it relates to Summon and other tooling in this space.

### What you are seeing

>  I see the following temp file

When you use `--env-file @SUMMONENVFILE` on a non-Linux OS, this is the behavior that is expected: a tempfile is created with the content of the retrieved variables in a location and with appropriate permissions that only allow the user that started summon see them so that Docker can load those variables properly. If you were on Linux, we would use a bit more-secure method of [passing in data over `DEVSHM`](https://github.com/cyberark/summon/blob/master/internal/command/temp_factory.go#L9-L10) but MacOS does not have a good analogue though it's as secure as you consider Linux ACLs.

This allows the user who was able to run `summon` and retrieve the credentials able to see and/or manipulate them during the subprocess run but any other user (other than `root`) on your machine is not able to see nor use those. For other users to read your secrets, they must be able to impersonate the original user running `summon` or find a way to circumvent filesystem ACLs. In most deployments, the "host" running the container is usually considered secure and the insecure workload is in the container so `summon` fills that security gap nicely by hiding how the secrets were retrieved and from where but it's limited when you consider both the container _and_ the host insecure.

> which gives away all the secrets!

It's a bit of a tricky wording there. `summon` doesn't give away the secrets because the only user that can read this file should be the user that successfully ran `summon` in the first place and the one able to retrieve those secrets from the provider anyways.

### Increasing security posture

Now, all of the architectural `summon` details apart, if you are needing higher levels of assurance in regards to security the traditional way (outside of moving to Linux that supports `DEVSHM`):

- Your container would be the one pulling the credentials directly from a separate machine hosting a credentials store (e.g. [Conjur / DAP](https://www.conjur.org/).
- Your container would use some sort of [authentication identity integration](https://docs.conjur.org/Latest/en/Content/HomeTilesLPs/LP-Tile4.htm#Authenticators) to provide you with authentication identity.
- You would use `summon` or more likely direct APIs (e.g. [Python3 APIs](https://github.com/cyberark/conjur-api-python3))  to pull the value from that secrets store.

If you want to take secrets out of the app itself completely, you could try something else like [Secretless Broker](https://secretless.io/). This tool injects secrets directly between your client and the backend and you don't need to worry about the app leaking data at all since all the secrets are contained within the broker.

### Weakest links

This is a complete sidenote but something to keep in mind as well is that usually the weakest link in security is not always obvious. If I correctly read your CLI invocation, there is nothing `summon` would be able do on your setup that couldn't be bypassed using a root-mount privileged docker container that has full visibility into the whole machine. 

Try running the following snippet on your machine (it probably won't ask for a password):
```sh-session
$ docker run --rm -it -v /Users:/host_users debian:stable-slim bash -c 'ls -la /host_users'
```
😄 

Anyways, I probably wrote too much but I hope this brings a bit of clarity of what this tool does and how.
Srdjan

**Comment by rami013** [comment]
Thanks very much for the details, very helpful! I'd definitely consider these when designing our own implementation.
