### ISSUE TITLE
Feature: generate predictable file names when exposing secrets as `!file`

### ISSUE THREAD

**Issue by sontags** [cyberark/summon#180]
## Is your feature request related to a problem? Please describe

We currently try to solve an issue where we need to populate secrets into Kubernetes. We already use `gopass` and `summon` for several similar problem and try to stick with this tooling. For Kubernetes we use `kustomize`/`kubectl apply -k`.

A way to generate secrets using `kustomize` are `secretGenerators` (see https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md). They allow to provide an `env` file. This could be provided via summon and the `!file:var` option. However `kustomize` only allows to provide the filename of the `env` file as a static string while summon generates a file and provides the generated file name via environment variable. In order to easily combine the two tools it would be helpful to generate the temporary files in a predictable manner.

## Describe the solution you would like

Instead of creating a file named `/dev/shm/.summonXXXXXXXXX` a file named `/dev/shm/.summon_ENV_FILE_FOO` could be generated for the following `secrets.yml`:

```
ENV_FILE_FOO: !var:file env/foo
``` 

To control the behavior a flag must be added to summon which by default keeps the current behavior.

## Describe alternatives you have considered

We currently use a little wrapper `exec.sh` to achieve a similar behavior:

```
#!/bin/bash

for FILE in $(env | grep "ENV_FILE"); do
    NAME=$(echo $FILE | cut -d'=' -f1)
    DEST=$(echo $FILE | cut -d'=' -f2)
    ln -s $DEST /dev/shm/$NAME
done

eval "$@"

for FILE in $(env | grep "ENV_FILE"); do
    NAME=$(echo $FILE | cut -d'=' -f1)
    rm /dev/shm/$NAME
done
```

and then:

```
summon -p ~/.bin/summon-gopass ./exec.sh cat /dev/shm/ENV_FILE_FOO
```

## Additional context

If the feature would be considered to be helpful I would happily provide a PR.

**Comment by sgnn7** [comment]
Hey @sontags,
Thanks for providing your use case and for using Summon!

As for the suggestion I think that as-is it may not be very feasible from a security standpoint without opening up some serious attack vectors:
- Because `secrets.yml` files are not usually as secured as the executable itself, allowing configuration via that method will reduce the security posture since it will allow unprivileged users to decide where the secrets will be written to (I'm guessing `/dev/stdout` could be set as a target).
- Use of a CLI switch to provide the file's full basename provides somewhat better security but it could be used to maliciously overwrite known target files if abused (e.g. `../../etc/passwd`), especially if `summon` runs privileged.
- Use of a CLI switch to provide the file's suffix also provide a bit better security but it could be used to place files into unwanted directories. I'm guessing this might not work depending on the system but maybe you can set the path to 
- Ability to change the target directory with either method opens up the same overwriting vector as the previous issue. It also may move the file into a less secure spot on the system (vs `/dev/shm` on Linux).
- All of these options then have to parse the provided path _very_ carefully to avoid directory traversal (e.g. 
`ENV_FILE_FOO=%2e%2e%5c%2e%2e%5cpasswd`)

With all this in mind, I believe that we need another option. I'll think a bit more on this but I am open to suggestions as to how we can get something usable for your use case out of `summon` without impacting security.

Srdjan

**Comment by sontags** [comment]
Hey @sgnn7,

Thanks for the list of your concerns. I have learned a lot from those few lines. 

While testing the workaround I have described we noted that this does not work as well. The reason for this is the fact that `kustomize` only accepts env files that are a) proper files (no cheating with symlinks) and b) are located in or below the directory were `kustomize` reads its `kustomize.yaml` file. 

Having this and your concerns in mind I believe there is no proper solution to the problem that involves any changes to `summon`. Most likely the missing link between `gopass` (or any other secret store) and `kustomize/kubectl` is to implement a _secret generator plugin_ as described in https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md. That could either mean to write a plugin that interacts with `gopass` directly or a plugin that consumes environment variables (where `summon` would come handy again).

However, thanks for digging into my request and explaining the downsides of my suggestion! Feel free to close the issue as the request most likely does not solve any real life issue.

Daniel

**Comment by sgnn7** [comment]
@sontags Fair enough and thank you for letting us know about this use case - it's important for us to know `summon` is used in the wild!

I'll close the issue for now on this but feel free to reopen it if you can think of a way to do this (and I'll do the same).

PS: If you're using these secrets to connect to a database and/or HTTP APIs, take a look at our sister project [Secretless Broker](https://github.com/cyberark/secretless-broker) as it may collapse a large number of your tools into a single sidecar 😄 

Srdjan
