### ISSUE TITLE
Spike: scaling Summon installs into Kubernetes volume mounts

### ISSUE THREAD

**Issue by izgeri** [cyberark/summon#204]
We've written up a short POC of [injecting Summon into Kubernetes volume mounts](https://gist.github.com/doodlesbykumbi/f4d241cf14d62ff588b419b1dcfcbf4c) to improve ease of install / use in Kubernetes. At current, we recommend customers update their application images to include the Summon binary when using Summon, but we'd ideally like to move to a system where Summon can be used with Kubernetes applications with no code changes.

In this spike, we'd like to understand better how to scale Summon installs into Kubernetes volume mounts, and what the implications of operating Summon this way at scale would be. In particular, how can we avoid having 10,000 Summon binaries for 10,000 volume mounts? Are there any other important considerations at scale?

AC:
- [ ] There is a write-up (in a gist or comment on this issue) that goes into the implications of injecting Summon binaries into volume mounts at scale, with a list of important considerations, a breakdown of the pros/cons of the different approaches that we could take to managing this, and a recommendation for a path forward.

**Comment by doodlesbykumbi** [comment]
Volume mounts avoid the current need to add a Summon binary to every single application container image. Ideally the source of the volume mounts is pre-populated with data, and that data can be shared between pods to avoid duplication.

Broadly speaking the approaches fall into 2 categories, and take into account the [different types of volumes available in Kubernetes](https://kubernetes.io/docs/concepts/storage/volumes). Ephemeral volume types have a lifetime of a pod, but persistent volumes exist beyond the lifetime of a pod. Certain types of volume are not appropriate for the use case .e.g. Secrets or ConfigMaps, these rely on the raw binary data being posted via the API server to etcd (or whatever the backing storage for k8s is), Summon binaries exceed the limits of typical configurations.

Approaches:

1. On pod creation an init container populates an [`emptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume. This is flexible since the installation script can be inlined in the pod manifest. It's easier to lose track of the versions of Summon running across the different pods. Storage consumed scales linearly with the number of workloads. Volumes are deleted when the pod is terminated. Time added to pod start while init container runs.
2. A pipeline exists for populating some persistent volume. The type of the persistent volume is at the discretion of the user. The user must take into account the constraints of certain persistent volume types. Volume types associated with particular nodes (e.g. [Host path](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)) are at risk of being unusable by the pod when the node is unhealthy/unavailable. Storage consumed should be constant(, we need to confirm how mounting works?). Zero impact (maybe time to mount?) on pod startup. Centralised storage for binary and so easier to manage version of Summon in production.

**Comment by doodlesbykumbi** [comment]
For (1), here are some ways the init container could populate an emptyDir volume:

a. Download (e.g. with wget) a release version of the Summon binary in real time (e.g. based on a desired version) and move to `emptyDir`. This incurs a time penalty of fetching the binary at every time at pod startup.

b. Include Summon binaries in the init container image, and the init container simply copies this binary to a shared `emptyDir` volume. This incurs the time penalty of downloading the container image the first time on any node, then the storage penalty of keeping it on any node.

**Comment by andytinkham** [comment]
We should also be aware of the need to verify a Summon binary if it's on a persistent volume. There should be some check to ensure it's the expected summon binary and not, for example, a malicious fake placed by an attacker. Persistent volumes change the trust boundaries of the system. They might still be the right solution, but different security risks and mitigations will apply.
