### ISSUE TITLE
Default value for substitution variable

### ISSUE THREAD

**Issue by anton-shirikov** [cyberark/summon#38]
It would be useful to support default values for substitution variables in secrets.yml using bash syntax:
```
ENV=${a:-default}
```
This will allow to have more flexibility without having to specify a lot of parameters that you don't care about.

**Comment by dustinmm80** [comment]
Hi Anton, is this still something you would like from Summon?

**Comment by anton-shirikov** [comment]
Yes, I think it might be useful in some cases

**Comment by dividedmind** [comment]
While it might be useful, I don't think this is a good syntax. Not sure what a better one would be.

**Comment by ryanprior** [comment]
Syntax proposal:

```yaml
MONGODB_PASS:
  var: myapp/prod/mongodb/password
  default: admin #😭 
```

**Comment by dannyOhNo** [comment]
Any update on this?

**Comment by sgnn7** [comment]
@dannyOhNo I can take a look at how feasible this is maybe this Friday (I can't make any promises on if I will have time to implement this change).

**Comment by sgnn7** [comment]
I have a PR open for this now. Given the complexity of changes needed to use the non-inlined YAML, I oped for supporting the following syntax in the code:
```yaml
SOME_VAR: !var:default='mydefault' /path/to/var
```

**Comment by ryanprior** [comment]
Oof, inventing new ways to store structured data in YAML by parsing the suffix of a type annotation tag really seems like abuse of the format. In particular, the YAML specification says about tags that they "must specify the expected node kind" which is orthogonal to the concept of a default value.

I still think my 2017 proposal looks great, but it might be inappropriate because it removes the `var` tag which is well-established by now. Let's look at an alternative that adopts common YAML practices instead of reinventing them. Updated proposal:

```yaml
SOME_VAR: !var {/path/to/var, default: mydefault}
```

###### Advantages
- uses the `var` tag with a standard YAML dict
- succinct & explicit
- future proof: easy to add more or different metadata beyond a default
- doesn't introduce a new nonstandard way to add structured data to a YAML file

**Comment by sgnn7** [comment]
@ryanprior so there are multiple aspects here that make alternatives difficult:
- Your 2017 proposal:
```
MONGODB_PASS:
  var: myapp/prod/mongodb/password
  default: admin #😭 
```
  - This requires a fundamental change on how the whole secretsyaml module functions as it doesn't currently evaluate nor iterate over inner children. This is the biggest blocker from my perspective as internal dedicated time to work on this project is not really there for this level of change.
  - `var` part is extremely ambiguous. Does that mean that the path is a var? If it's not does that mean that we can do something rather confusing like `var: !var myapp/prod/mongodb/password`?
-----
- Your last comment proposal:
```
SOME_VAR: !var {/path/to/var, default: mydefault}
```
  - If we start meddling into the literal variable paths themselves, we will inevitably hit a problem where we are no longer faithfully passing down the variable name which then adds the complexity of escaping characters and defining the variable path structure that additionally needs to be considered.
-----
- @anton-shirikov 's proposal:
```
ENV=${a:-default}
```
  - This doesn't fit the yaml declaration parsing style (it's Bash-like) so it's very unintuitive. In addition, the default setter for a variable in Bash is probably one of the ones that syntactically is the oddest one so even for Bash it's odd (`:` set to, `-` delete?)
-----
- The PR implementation:
```
SOME_VAR: !var:default='mydefault' /path/to/var
```
- Requires minimal code change
- Does not step into the literal value of the variable
- [Is within spec](https://yaml.org/spec/1.2/spec.html#id2764295) (though I agree that it's a bit of a loose fit):
  - `... local tags are specific to a single application... [they] start with “!” ...`
  - `... a tag may provide additional information such as the set of allowed content values for validation, a mechanism for tag resolution, or _any other data that is applicable to all of the tag’s nodes_.`

@ryanprior I get your point of view but hopefully this will explain the reasoning behind the particular direction that I took.

**Comment by izgeri** [comment]
I wonder if this is an argument for pushing forward with the `summon2` that is packaged as part of [secretless](https://github.com/cyberark/secretless-broker) - the config has the potential to be much more flexible there, similar to how the secretless config is structured. I haven't seen a proposal for this yet, but it might look something like:
```
secrets:
  address:
    from: conjur
    get: /path/to/db/address
  username: my-literal-username
  password:
    from: env
    get: DB_PASSWORD
    default: SuperSecret!
```

ie we could enable multiple providers in a single secrets.yml, support defaults, and in general be more flexible.

however, I don't have a timeline for when `summon2` will be officially available, and the changes made by @sgnn7 enable setting a default value and are relatively simple given the current architecture of summon. I'm interested to know whether the current test cases do a good job of covering the potential ways end users might try to use `default` (and the unhappy paths they might encounter) - but if that looks good, I can't see the harm in adding this feature in this form right now, since it makes default values possible in a way that is relatively in line with the current implementation.

I would love to see us move toward using the simpler `summon2` at some point soon, too.

**Comment by sgnn7** [comment]
Closing as "released" for the initial implementation of this. Feel free to open new issues for better syntax if needed. v0.8.1 can be found [here](https://github.com/cyberark/summon/releases/tag/v0.8.1).
