### ISSUE TITLE
"Provider of your choice" URL is broken in README.me

### ISSUE THREAD

**Issue by infamousjoeg** [cyberark/summon#46]
Under the "Install" section, the "Provider of your choice" URL points to http://conjurinc.github.io/summon/#providers which is currently a broken link.

**Comment by dustinmm80** [comment]
Thanks for bringing this up Joe!

The URL has changed completely, since we moved the github repo.

https://cyberark.github.io/summon/ is the new docs page on the `gh-pages` branch. We should find/replace the URL in this project. We are probably referencing the URL from other projects too, that we should fix up. I'm not sure if summon is up on conjur.org yet.

Additionally, if we're going to improve the `gh-pages` along with the README, can we get rid of that branch and just have a `docs/` folder? That would make the docs easier to work on. https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by doodlesbykumbi** [comment]
#48 fixes this
