### ISSUE TITLE
Summon fails to pass SIGTERM to child process

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/summon#70]
Summon fails to pass signals into the child process, instead, it simply terminates the child process when receiving a kill signal. This means it can't be used in environments that depend on graceful shutdown of an application (like rolling restarts in OpenShift/Kuberneted).

**Desired Result** : Summon passes the common kill signals to the child process, waiting a reasonable period of time to terminate the process, before killing it.

**Comment by jepperson2** [comment]
Is there any update on this issue? I just ran into some issues where Summon does not kill its grandchild process. For example, a process tree that looks like `Summon -> Summon -> A -> B` will leave the `A -> B` process subtree still running upon the outermost Summon being killed.

**Comment by sgnn7** [comment]
@jepperson2 So I looked into this (the issue precedes my tenure at CyberArk) and from what I can see in the code:
- We load Summon
- The child process is launched with [`execve`](http://man7.org/linux/man-pages/man2/execve.2.html) 
- The child process swaps completely with Summon as the runner process (summon code is unloaded and doesn't exist at this point in the process space)

If you go by the container recommendations, you won't launch multiple processes within the container so this works fine since the signals are received directly by the "main" process (`A` in your example). If you want this chained signal passing and process reaping (aka [PID1 problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/)) which occurs when you daisy-chain processes, the easiest way to do this would be to add [`--init`](https://docs.docker.com/engine/reference/run/#specify-an-init-process) flag to your Docker container or add [tini](https://github.com/krallin/tini) as the parent process either before or after `summon`:
```
Either:
(running container with `--init`)
summon -> A -> B

Or:
tini -> summon -> A -> B

Or:
summon -> tini -> A -> B
```

Now, this is not to say that we can't build this functionality into `summon` but it would be much harder to ensure that we pass all the signals/events like some of the solutions that already have this functionality but let us know if this is something important enough that we should look into.

Hope this helps!

**Comment by jepperson2** [comment]
@sgnn7 From what I can tell the Summon process is not unloaded nor is the child process launched with execve. Summon [uses](https://github.com/cyberark/summon/blob/0a752fda90ecdb504d86fdf46bb905fe040bc85a/command/subcommand.go#L11-L17) the "os/exec" package, which unlike the syscall.Exec function, does not replace the parent process with the child. Here's an example of the process tree in my environment:

![summon process tree](https://user-images.githubusercontent.com/3820725/49412627-f15a2b80-f721-11e8-8816-c682eba8051d.png)

If I run `kill 19911` the remaining 3 process layers underneath the that outermost Summon remain running.

**Comment by jepperson2** [comment]
It would be desirable if Summon did use `execve` via the `syscall.Exec` function as this would unload the Summon process and leave only the child process running.

**Comment by sgnn7** [comment]
@jepperson2 Ah, excellent catch! I incorrectly thought that I saw that it was `syscall.Exec`ing (I think I must have seen that import in a different file then). Let me talk to some of the people on the team more familiar with Summon to see if there's any heartburn about switching it to that. If not, I think I have some internal Golang code I wrote already to do the basic signal passing and process reaping elsewhere that we might be able to shoehorn in pretty easily.

**Comment by sgnn7** [comment]
@jepperson2 This issue is now superseded by #83 since there's a lot more work (mostly cleanup) being done as part of it. PR is now open as well at https://github.com/cyberark/summon/pull/84.

Closing as the parent issue should solve this one after implementation.

**Comment by sgnn7** [comment]
@jepperson2 The release [v0.6.9](https://github.com/cyberark/summon/releases/tag/v0.6.9) is available. Give it a try and let me know if it works :)
